{{- if .Values.snapshotsEnabled }}
{{- range .Values.configuration.volumeSnapshotLocation }}
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: {{ .name }}
  labels:
    app.kubernetes.io/name: {{ include "velero.name" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
    helm.sh/chart: {{ include "velero.chart" $ }}
spec:
  provider: {{ .provider }}
{{ with .config }}
  config:
  {{- with .region }}
    region: {{ . }}
  {{- end }}
  {{- with .apitimeout }}
    apiTimeout: {{ . }}
  {{- end }}
  {{- with .resourceGroup }}
    resourceGroup: {{ . }}
  {{- end }}
  {{- with .subscriptionId }}
    subscriptionId: {{ . }}
  {{- end }}
  {{- with .snapshotLocation }}
    snapshotLocation: {{ . }}
  {{- end}}
  {{- with .project }}
    project: {{ . }}
  {{- end}}
{{- end }}
{{- end }}
---
{{- end}}
